name: connections
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  shared_preferences: ^2.5.2
  cupertino_icons: ^1.0.8
  lottie: ^1.2.1
  fl_chart: ^0.63.0
  provider:
  intl: ^0.20.2
  flutter_svg:
  syncfusion_flutter_charts: ^28.2.7
  flutter_launcher_icons:
  assets_audio_player:
    git:
      url: https://github.com/florent37/Flutter-AssetsAudioPlayer

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_density: 16
  max_density: 512

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/tap.mp3
    - assets/confetti.json

  fonts:
    - family: PressStart2P
      fonts:
        - asset: font/PressStart2P-Regular.ttf