class Trivia {
  List<String> triviaStatements = [
    'The average human body is estimated to have 37.2 trillion human cells.',
    'The human egg cell is one of the largest cells, with a size of 0.1 millimeters across.',
    'The inside of a cell is like an underwater city, with tiny structures (organelles and proteins) floating and swimming about.',
    'Imaging just one cell at nanometer resolution takes up the same amount of data as about 83,000 photos on your phone.',
    'Cells in your blood regenerate every two months.',
    'Some of the cells in your brain and eyes do not regenerate at all! So better take good care of them.',
    'Each time the human DNA is replicated, approximately 120,000 copying mistakes are made across the 6 billion bases.',
    'Although most errors in DNA replication do not amount to significant genomic changes, these could accumulate for a lifetime as your cells divide.',
    'A single eukaryotic cell spends about 90% of its life in interphase, where it grows, copies its DNA, and prepares for division.',
    'DNA replication is essential for cell division, ensuring that each new cell gets an exact copy of genetic information.',
    'Mitosis is incredibly fast; some cells, like skin cells, can complete it in just an hour.',
    'A eukaryotic cell goes through four main stages in its life cycle: G1, S, G2, and M phase.',
    'DNA replication ensures that every new cell receives an exact copy of genetic information.',
    'The double helix structure of DNA must unwind before replication can begin.',
    'Helicase is the enzyme responsible for “unzipping” the DNA double helix by breaking hydrogen bonds between complementary bases.',
    'A typical human body starts from a single fertilized egg that undergoes millions of cell divisions.',
    'DNA polymerase is the enzyme that adds new nucleotides to a growing DNA strand during replication.',
    'The replication fork is the Y-shaped region where DNA strands are being separated and copied.',
   'The leading strand is synthesized continuously, while the lagging strand is synthesized in short segments called Okazaki fragments.',
    'DNA ligase joins Okazaki fragments on the lagging strand to create a continuous DNA strand.',
     'RNA primers, made by primase, serve as starting points for DNA polymerase to begin DNA synthesis.',
    'DNA replication occurs in multiple locations simultaneously due to the formation of replication bubbles.',
    'DNA strands from reattaching during replication.',
    'The central dogma of molecular biology describes the flow of genetic information from DNA to RNA to proteins.',
    'Messenger RNA or mRNA carries the genetic instructions from DNA to the ribosome for protein synthesis.',
    'Ribosomal RNA or rRNA combines with proteins to form ribosomes, the site of protein synthesis.',
    'Transfer RNA or tRNA transports amino acids to the ribosome and matches them with the appropriate mRNA codon.',
    'The nitrogenous bases in DNA are adenine, thymine, cytosine, and guanine, while RNA contains uracil instead of thymine.',
    'DNA strands run in opposite directions, referred to as antiparallel orientation.',
    "DNA polymerase can only add nucleotides in the 5’ to 3’ direction, requiring different replication mechanisms for each strand.",
    'The genome is the complete set of genetic material in an organism.',
    'Chromosomes are condensed structures made of DNA that store genetic information.',
    'Mutations in DNA replication can lead to genetic variations or diseases.',
    'DNA ensures that every new generation of cells has the same genetic instructions as the previous one.',
    'The M phase encompasses mitosis and cytokinesis, leading to the formation of two daughter cells.',
    'During the G1 phase, the cell grows and duplicates its organelles, excluding chromosomes.',
    'The S phase is characterized by DNA replication, resulting in duplicated genetic material.',
    'In the G2 phase, the cell continues to grow and prepares for mitosis.',
    'Mitosis is divided into prophase, metaphase, anaphase, and telophase.',
    'During prophase, chromatin condenses into visible chromosomes.',
    "In metaphase, chromosomes align at the cell’s equatorial plane.",
    'Anaphase involves the separation of sister chromatids to opposite poles.',
    'During the S phase, DNA synthesis occurs, duplicating the genetic material.',
    'The G2 phase is a period of further growth and preparation for mitosis.',
    'The mitotic phase consists of mitosis and cytokinesis, leading to cell division.',
    'Cytokinesis divides the cytoplasm, resulting in two distinct daughter cells.',
    'The G0 phase is a resting state where cells exit the active cell cycle.',
    'Neurons often remain in the G0 phase permanently.',
    'Checkpoints in the cell cycle ensure each phase is accurately completed before proceeding.',
   'The spindle assembly checkpoint during metaphase verifies proper chromosome attachment to spindle fibers.',
    'Errors in cell cycle regulation can lead to uncontrolled cell division, a characteristic of cancer.',
    'The duration of the cell cycle varies among different cell types and organisms.',
    'Stem cells have the unique ability to continuously divide and produce new cells.',
    'During prophase, the mitotic spindle begins to form as centrosomes move to opposite poles.',
    'The nuclear envelope breaks down during prometaphase, allowing spindle fibers to attach to chromosomes.',
    'The metaphase plate is an imaginary plane equidistant from the two spindle poles where chromosomes align during metaphase.',
    'During telophase, chromosomes begin to decondense back into chromatin.',
    'Plant cells undergo cytokinesis by forming a cell plate that eventually develops into a new cell wall.',
    'The cell cycle is tightly regulated by a series of signaling pathways to maintain proper cell function.',
    'Mutations in genes that regulate the cell cycle can lead to various diseases, including cancer.',
    'Cell cycle arrest allows time for DNA repair mechanisms to correct damage before cell division continues.',
    'The entire human body regenerates nearly all its cells every 7 to 10 years, though some cells, like neurons, last a lifetime.',
    'Some cells, like liver cells, can exit G0 and re-enter the cell cycle when needed for tissue repair.',
    'Polyploid cells have more than two sets of chromosomes and are common in plants but rare in animals.',
    'The synaptonemal complex forms during prophase I of meiosis to facilitate crossing over.',
    'Cells spend most of their time in interphase, not mitosis, despite mitosis being more well-known.',
    'Crossing over during meiosis increases genetic diversity by exchanging DNA between homologous chromosomes.',
    'During meiosis I, homologous chromosomes separate, while in meiosis II, sister chromatids separate.',
    'Some chemotherapy drugs target rapidly dividing cells by interfering with mitosis.',
    'Binary fission in prokaryotes is similar to mitosis but does not involve a complex spindle apparatus.',
    'Meiosis, which produces gametes, involves two rounds of division and results in four non-identical cells.',
    'Telomeres, the protective caps on chromosome ends, shorten with each cell division and contribute to aging. ',
    'The enzyme telomerase helps extend telomeres in certain cells, such as stem cells and cancer cells.',
    'During anaphase, motor proteins pull chromatids apart using microtubules as tracks.',
    'Cancer cells often bypass normal cell cycle checkpoints, allowing uncontrolled proliferation.',
    'Apoptosis, or programmed cell death, eliminates damaged or unnecessary cells to maintain tissue health.',
    'The p53 protein, often called the “guardian of the genome,” plays a crucial role in preventing damaged cells from dividing.',
    'Cyclins and cyclin-dependent kinases (CDKs) regulate cell cycle progression by controlling transitions between phases. ',
    'Cells in multicellular organisms communicate through chemical signals to coordinate division and function.',
  ];
}
    

// class Trivia {
//   List<String> triviaStatements = [
//     'The average human body is estimated to have 37.2 trillion human cells.', 
//     'The human egg cell is one of the largest cells, with a size of 0.1 millimeters across.',
//     'The inside of a cell is like an underwater city, with tiny structures (organelles and proteins) floating and swimming about.',
//     'Imaging just one cell at nanometer resolution takes up the same amount of data as about 83,000 photos on your phone.',
//     'Cells in your blood regenerate every two months.',
//     'Some of the cells in your brain and eyes do not regenerate at all! So better take good care of them.',
//     'Each time the human DNA is replicated, approximately 120,000 copying mistakes are made across the 6 billion bases.', 
//     'Although most errors in DNA replication do not amount to significant genomic changes, these could accumulate for a lifetime as your cells divide.',
//     'A single eukaryotic cell spends about 90% of its life in interphase, where it grows, copies its DNA, and prepares for division.',
//     'DNA replication is essential for cell division, ensuring that each new cell gets an exact copy of genetic information.'
//   ];
// }